version: "3.8"

services:
  login:
    image: csse584:hadoop-word-score
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the current working directory at /usr/local/src.
      - type: bind
        source: .
        target: /usr/local/src
      # Mount the Yelp Academic Dataset at the expected location.
      - type: bind
        source: ${YELP_HOME}
        target: /usr/local/share/yelp
        read_only: true
